#!/usr/bin/env bash
# Creates PID file, runs infinite loop, and handles signals

echo $$ > /var/run/myscript.pid

trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!";' SIGINT

while true
do
    echo "To infinity and beyond"
    sleep 2
done
